### ISSUE TITLE
cmux: Can not set the auto balancer: CMUX::CMUXHBaseToolBalancerError

### ISSUE THREAD

**Issue by thinker0** [kakao/cmux#2]
@junegunn @nukiee @Knext @violetblue 
```
2018-12-21 10:43:32 Are you sure you want to ROLLING RESTART on the above roles (y|n)? y
2018-12-21 10:43:34 Set SECONDS TO SLEEP between batches (>= 0 secs): 0
2018-12-21 10:43:36 Set the MAX WAIT TIME after executing the RESTART command (>= 180 secs): 180
2018-12-21 10:43:37 Do you want to proceed with INTERACTIVE MODE (y|n)? n
2018-12-21 10:43:39 Disable HBase balancer
2018-12-21 10:43:40 └── java -jar /Users/thinker0/line/cmux/lib/hbase-tools/hbase-manager-1.2-1.4.2.jar assign beta014:2181 balancer false  | tail -1
2018-12-21 10:43:41 Do you want to turn on auto balancer (y|n)? n
2018-12-21 10:43:42 Finish
cmux: Can not set the auto balancer: CMUX::CMUXHBaseToolBalancerError
      /Users/thinker0/line/cmux/lib/cmux/commands/rolling_restart.rb:233:in `rescue in disable_hbase_balancer'
      /Users/thinker0/line/cmux/lib/cmux/commands/rolling_restart.rb:224:in `disable_hbase_balancer'
      /Users/thinker0/line/cmux/lib/cmux/commands/rolling_restart.rb:149:in `prepare_rolling_restart_for_rs'
      /Users/thinker0/line/cmux/lib/cmux/commands/rolling_restart_hosts.rb:102:in `rolling_restart'
      /Users/thinker0/line/cmux/lib/cmux/commands/rolling_restart_hosts.rb:20:in `process'
      /Users/thinker0/line/cmux/lib/cmux.rb:44:in `run'
      /Users/thinker0/line/cmux/bin/cmux:4:in `<main>'
```

**Comment by junegunn** [comment]
Hi, have you tried manually running the command shown in the log? (`java -jar ...`) Do you see any error messages?

**Comment by thinker0** [comment]
```
thinker0$ java -jar /Users/thinker0/line/cmux/lib/hbase-tools/hbase-manager-1.2-1.4.2.jar assign beta014-aac-jp2p-dev.lineinfra-dev.com:2181 balancer false
Picked up _JAVA_OPTIONS: -Dfiles.encoding=UTF-8
Connecting to beta014-aac-jp2p-dev.lineinfra-dev.com:2181
Automatic balancer is already turned off.
```
이것 때문에 나는 걸까요 ?
Picked up _JAVA_OPTIONS: -Dfiles.encoding=UTF-8

**Comment by junegunn** [comment]
코드를 봤는데 에러 체크 방식이 조금 이상하네요. 아래 패치 적용하면 동작하는지 보시겠어요?

```diff
diff --git a/lib/cmux/utils.rb b/lib/cmux/utils.rb
index a9ec0fd..5585988 100644
--- a/lib/cmux/utils.rb
+++ b/lib/cmux/utils.rb
@@ -76,7 +76,7 @@ module CMUX
       # Run command.
       def run_cmd_capture3(cmd)
         out, err, status = Open3.capture3(cmd)
-        return out.chomp if err.to_s.empty?
+        return out.chomp if status.success?
         yield err, status
       end
```

**Comment by thinker0** [comment]
@junegunn 감사합니다. 잘작동 하는거 같네요. ^_______^

**Comment by junegunn** [comment]
확인 감사합니다. 수정했어요.
